apiVersion: v1
kind: Pod
metadata:
  name: simple-api
  labels:
    name: simple-api
spec:
  containers:
  - name: simple-api
    image: abhishekashihek/simple-api   
    ports:
    - containerPort: 5500